db = db.getSiblingDB("quizdini");
try {
  db.states.insertMany(
    [
      { stateCode: "AK", stateName: "Alaska" },
      { stateCode: "AL", stateName: "Alabama" },
      { stateCode: "AR", stateName: "Arkansas" },
      { stateCode: "AZ", stateName: "Arizona" },
      { stateCode: "CA", stateName: "California" },
      { stateCode: "CO", stateName: "Colorado" },
      { stateCode: "CT", stateName: "Connecticut" },
      { stateCode: "DC", stateName: "District of Columbia" },
      { stateCode: "DE", stateName: "Delaware" },
      { stateCode: "FL", stateName: "Florida" },
      { stateCode: "GA", stateName: "Georgia" },
      { stateCode: "GU", stateName: "Guam" },
      { stateCode: "HI", stateName: "Hawaii" },
      { stateCode: "IA", stateName: "Iowa" },
      { stateCode: "ID", stateName: "Idaho" },
      { stateCode: "IL", stateName: "Illinois" },
      { stateCode: "IN", stateName: "Indiana" },
      { stateCode: "KS", stateName: "Kansas" },
      { stateCode: "KY", stateName: "Kentucky" },
      { stateCode: "LA", stateName: "Louisiana" },
      { stateCode: "MA", stateName: "Massachusetts" },
      { stateCode: "MD", stateName: "Maryland" },
      { stateCode: "ME", stateName: "Maine" },
      { stateCode: "MI", stateName: "Michigan" },
      { stateCode: "MN", stateName: "Minnesota" },
      { stateCode: "MO", stateName: "Missouri" },
      { stateCode: "MS", stateName: "Mississippi" },
      { stateCode: "MT", stateName: "Montana" },
      { stateCode: "NC", stateName: "North Carolina" },
      { stateCode: "ND", stateName: "North Dakota" },
      { stateCode: "NE", stateName: "Nebraska" },
      { stateCode: "NH", stateName: "New Hampshire" },
      { stateCode: "NJ", stateName: "New Jersey" },
      { stateCode: "NM", stateName: "New Mexico" },
      { stateCode: "NV", stateName: "Nevada" },
      { stateCode: "NY", stateName: "New York" },
      { stateCode: "OH", stateName: "Ohio" },
      { stateCode: "OK", stateName: "Oklahoma" },
      { stateCode: "OR", stateName: "Oregon" },
      { stateCode: "PA", stateName: "Pennsylvania" },
      { stateCode: "PR", stateName: "Puerto Rico" },
      { stateCode: "RI", stateName: "Rhode Island" },
      { stateCode: "SC", stateName: "South Carolina" },
      { stateCode: "SD", stateName: "South Dakota" },
      { stateCode: "TN", stateName: "Tennessee" },
      { stateCode: "TX", stateName: "Texas" },
      { stateCode: "UT", stateName: "Utah" },
      { stateCode: "VA", stateName: "Virginia" },
      { stateCode: "VT", stateName: "Vermont" },
      { stateCode: "WA", stateName: "Washington" },
      { stateCode: "WI", stateName: "Wisconsin" },
      { stateCode: "WV", stateName: "West Virginia" },
      { stateCode: "WY", stateName: "Wyoming" }
    ],
    { ordered: true }
  );
} catch (e) {
  print(e);
}
